safe: false

# build settings
markdown: kramdown
lsi: false

title: "Jiacheng Miao"
description: ""
url: "https://jmiao24.github.io" # replace by your site's url
twitter_username: Jiacheng_Miao
google_scholar: https://scholar.google.com/citations?user=cLIcazgAAAAJ&hl=en
github_username:  jmiao24 # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "Jiacheng Miao"
address: "Madison, USA"
email: "your@email.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
